//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Appointment
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Enter DateTime")]
        [Display(Name = "Date And Time")]
        public string Time { get; set; }

        [Required(ErrorMessage = "Enter Reason")]
        [Display(Name = "Reason")]
        public string Reason { get; set; }

        [Required(ErrorMessage = "Enter Doctor Email ID")]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Doctor Email address")]
        [MaxLength(50)]
        [RegularExpression(@"[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}", ErrorMessage = "Please enter correct email")]
        public string Doctor_email { get; set; }

        [Required(ErrorMessage = "Enter Patient Email ID")]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Patinet Email address")]
        [MaxLength(50)]
        [RegularExpression(@"[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}", ErrorMessage = "Please enter correct email")]
        public string Patient_email { get; set; }
    }
}
