//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class doctor
    {   
        [Required(ErrorMessage ="Enter Doctor ID")]
        [Display(Name = "Doctor Govt. Registration ID")]
        public int did { get; set; }

        [Required(ErrorMessage = "Enter Doctor Name")]
        [Display(Name = "Doctor Name")]
        public string dname { get; set; }

        [Required(ErrorMessage = "Enter Doctor Age")]
        [Display(Name = "Doctor Age")]
        public Nullable<int> dage { get; set; }

        [Required(ErrorMessage = "Enter Doctor Gender")]
        [Display(Name = "Doctor Gender")]
        public string dgender { get; set; }

        [Required(ErrorMessage = "Enter Doctor Email")]
        [EmailAddress(ErrorMessage ="Invalid Email Address")]
        [Display(Name = "Doctor Email Address")]
        public string daddress { get; set; }

        [Required(ErrorMessage = "Enter Doctor Category")]
        [Display(Name = "Doctor Category")]
        public string dcategory { get; set; }

        [Required(ErrorMessage = "Enter Password")]
        [Display(Name = "Doctor Password")]
        public string password { get; set; }

        [Required(ErrorMessage = "Enter Confirm Password")]
        [System.ComponentModel.DataAnnotations.Compare("password",ErrorMessage ="Passwords not matched")]
        [Display(Name = "Doctor Confirm Password")]
        public string confirmpassword { get; set; }

     
        [Display(Name = "Doctor Status")]
        public string status { get; set; }
    }
}
