//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {   
        
        public int pid { get; set; }
        public string pname { get; set; }
        public Nullable<int> age { get; set; }
        public string address { get; set; }
        public string pgender { get; set; }
        public string pblood { get; set; }
        public string pemail { get; set; }
        public string password { get; set; }
        public string confirmpassword { get; set; }
    }
}
